### ISSUE TITLE
Entrevista con el cliente 

### ISSUE THREAD

**Issue by CamiloLafaurie** [CarsOk/ADSO2558427EQUIPO1MOVIL#4]
### Para: Iniciar con el proceso de recolección de información para dar comienzo de la página web y los requerimientos iniciales.

Criterios de aceptación: 

- [x] Debe asistir mínimo 2 integrantes del equipo. 
- [x] Deben de participar todos los empleados del restaurante para recolectar la mayor cantidad de informacion.
- [x] Analizar las falencias del restaurante y posibles soluciones.
- [x] Se debe recopilar información suficiente para iniciar con la creación de la página web.

**Comment by CamiloLafaurie** [comment]
el 05/02/2023 los integrantes del team scrum @CamiloLafaurie @RonaldoGomezCastro2558427 @Luislemus0109 se reunieron con el el dueño del restaurante Curb para recolectar la información necesaria para iniciar con la creacion del aplicativo mobil

**Comment by RonaldoGomezCastro2558427** [comment]
En este issues yo @RonaldoGomezCastro2558427 adjunto algunos criterios y un maquetado base sobre la aplicación móvil de la página curb
![f5d31d6f-549c-4d2d-ab53-b5b6e438f1ea](https://user-images.githubusercontent.com/110871505/216885190-dc330699-b528-4407-8948-67fb578f027e.jpg)
